#!/bin/bash

# AI Session Analyzer - GitHub Push Script
# This script helps you push your code to GitHub

echo "🚀 AI Session Analyzer - GitHub Push Helper"
echo "==========================================="
echo ""
echo "Your repository is ready to push!"
echo ""
echo "Repository: https://github.com/amirhosseinzolfi/AI-session-analyzor-chrome-extension.git"
echo "Branch: main"
echo ""
echo "📋 Files prepared:"
echo "  ✅ .gitignore (excludes sensitive data, logs, database)"
echo "  ✅ README.md (comprehensive documentation)"
echo "  ✅ LICENSE (MIT License)"
echo "  ✅ .env.example (environment template)"
echo "  ✅ requirements.txt (updated with all dependencies)"
echo ""
echo "🔐 To push to GitHub, you need to authenticate."
echo ""
echo "Option 1: Using GitHub CLI (recommended)"
echo "  gh auth login"
echo "  git push -u origin main"
echo ""
echo "Option 2: Using Personal Access Token"
echo "  1. Go to: https://github.com/settings/tokens"
echo "  2. Generate new token (classic) with 'repo' scope"
echo "  3. Run: git push -u origin main"
echo "  4. Username: amirhosseinzolfi"
echo "  5. Password: <your_token>"
echo ""
echo "Option 3: Using SSH"
echo "  1. Set up SSH key: https://docs.github.com/en/authentication/connecting-to-github-with-ssh"
echo "  2. Change remote: git remote set-url origin git@github.com:amirhosseinzolfi/AI-session-analyzor-chrome-extension.git"
echo "  3. Run: git push -u origin main"
echo ""
echo "After successful push, your code will be live at:"
echo "https://github.com/amirhosseinzolfi/AI-session-analyzor-chrome-extension"
echo ""
